# Generated by Django 5.2.8 on 2025-11-19 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_employee_id_customuser_license_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='license_number',
        ),
    ]
