# Generated by Django 5.2.8 on 2025-11-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_alter_patient_assigned_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="name",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="risk_score",
        ),
        migrations.AddField(
            model_name="patient",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="chronic_conditions",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="patient",
            name="first_name",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AddField(
            model_name="patient",
            name="lab_abnormalities",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="patient",
            name="last_name",
            field=models.CharField(default="Patient", max_length=100),
        ),
        migrations.AddField(
            model_name="patient",
            name="last_prediction_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="length_of_stay",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="patient",
            name="medication_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="patient",
            name="ml_risk_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="patient",
            name="previous_admissions",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="patient",
            name="risk_category",
            field=models.CharField(default="unknown", max_length=20),
        ),
        migrations.AddField(
            model_name="patient",
            name="social_support_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="patient",
            name="time_since_last_discharge",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="transportation_access",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="vital_signs",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="patient",
            name="last_visit",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="patient_id",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
